START TRANSACTION;
ALTER TABLE jobs 
ADD COLUMN name VARCHAR(255),
ADD COLUMN current_worker_id VARCHAR(50),
ADD COLUMN last_heartbeat_at TIMESTAMP NULL,
ADD COLUMN retry_count INT NOT NULL DEFAULT 0,
ADD COLUMN max_retries INT NOT NULL DEFAULT 3,
ADD COLUMN files VARCHAR(255),
ADD COLUMN job_state ENUM('READY','RUNNING','COMPLETED','ERROR','CANCELLED','TIMED_OUT') NOT NULL DEFAULT 'READY';
ALTER TABLE jobs MODIFY COLUMN last_modified_by VARCHAR(50) NULL;

UUPDATE jobs SET job_state = CASE 
  WHEN status = 'CREATED' THEN 'READY'
  WHEN status = 'PROCESSING' THEN 'RUNNING'
  ELSE 'READY' 
END;

UPDATE jobs SET name = CONCAT(job_type, '_', id);  
UPDATE jobs SET files = original_file WHERE original_file IS NOT NULL;

COMMIT;
